import { requireAdminMfa } from "@/lib/admin-guard";
import { invites, orgs } from "@/lib/mock/admin";
import { Head, Table, Panel, Badge } from "@/components/admin/ui";
import { InviteForm } from "@/components/admin/InviteForm";

export const metadata = { title: "Invites" };

export default async function InvitesPage() {
  await requireAdminMfa("/admin/invites");
  return (
    <div className="mx-auto max-w-6xl space-y-5">
      <Head eyebrow="Invite codes" title="Invites & onboarding" note="Worker codes are issued to an organisation with a use limit and expiry; the account still needs approval. Mother codes are generated by CHWs at enrolment." />
      <Panel title="New worker invite"><InviteForm orgs={orgs.filter((o) => o.type === "Health facility").map((o) => o.name)} /></Panel>
      <Table head={["Code", "Kind", "Organisation", "Issued", "By", "Used", "Expires"]}>
        {invites.map((i) => (
          <tr key={i.code}><td className="px-4 py-3 font-mono font-semibold text-emerald">{i.code}</td><td className="px-4 py-3"><Badge tone={i.kind === "mother" ? "coral" : i.kind === "chw" ? "green" : "violet"}>{i.kind}</Badge></td><td className="px-4 py-3 text-ink/80">{i.org}</td><td className="px-4 py-3">{i.issued}</td><td className="px-4 py-3 text-ink/80">{i.by}</td><td className="px-4 py-3 font-mono">{i.used}/{i.max}</td><td className="px-4 py-3">{i.expires}</td></tr>
        ))}
      </Table>
    </div>
  );
}
